### ISSUE TITLE
rvn fetch does not install packages into the "files" subdirectory if -o or --output is specified

### ISSUE THREAD

**Issue by EarldridgeJazzedPineda** [Ravenports/rvn#3]
When using rvn fetch, rvn is supposed to install packages into a subdirectory of the directory specified by -o or --output named "files". However, rvn installs packages directly to said directory. This causes the prebuilt option to break in ravenadm: https://github.com/Ravenports/ravenadm/issues/84

How to reproduce:
1. Run `mkdir ~/test`
2. Run `/raven/sbin/rvn fetch nano -o ~/test`

Expected behavior:
Fetched packages are installed into the ~/test/files directory

Actual behavior:
Fetched packages are installed into the ~/test directory and no subdirectory is created

**Comment by jrmarino** [comment]
probably rvn is correct but the command is wrong, e.g. it should be
```
/raven/sbin/rvn fetch nano -o ~/test/files
```

Thanks for the hint.

**Comment by jrmarino** [comment]
for now I've made the correction in ravenadm (not rvn)

**Comment by EarldridgeJazzedPineda** [comment]
Make sure that this fix is published in Ravensource, Ravenports, and the prebuilt catalog so that I can install it and continue working on my ports. Can you also fix the rvn-fetch(8) man page?

**Comment by jrmarino** [comment]
I'm still testing it. The status command is listing ports is listing prebuilt ports as "to-be-built" and I haven't been able to solve that yet.  The ravenadm release isn't ready yet (although nothing is stopping you from building from the latest hash).  what's wrong with rvn-fetch(8)?

Also, technically nothing is stopping you from working on your port if you just turn off the prebuilt option and let the dependencies build first.

**Comment by EarldridgeJazzedPineda** [comment]
> I'm still testing it. The status command is listing ports is listing prebuilt ports as "to-be-built" and I haven't been able to solve that yet. The ravenadm release isn't ready yet (although nothing is stopping you from building from the latest hash). what's wrong with rvn-fetch(8)?
> 
> Also, technically nothing is stopping you from working on your port if you just turn off the prebuilt option and let the dependencies build first.

The man page for rvn-fetch(8) mentions that when -o or --output is used, rvn will install packages to a subdirectory of the specified directory named "files". This is not the case; rvn installs packages directly to the specified directory.

**Comment by jrmarino** [comment]
hmm, if that's the case I need to review rvn after all.  if the man page is correct, then rvn needs to be fixed and the change the ravenadm reverted.
